apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - sealed-secrets.yaml

helmCharts:
  - name: sealed-secrets
    version: 2.17.1 # Check for latest version
    repo: https://bitnami-labs.github.io/sealed-secrets
    releaseName: sealed-secrets
    valuesFile: values.yaml
    namespace: kube-system
