#cloud-config
package_update: true
package_upgrade: false
packages:
  - curl
  - iptables
  - socat
  - conntrack-tools
  - ipset

runcmd:
  - |
    echo "Setting up K3s cluster..."

    # Common variables
    MASTER_IP="10.25.150.10"
    K3S_VERSION="v1.31.5+k3s.0"
    JOIN_TOKEN_PATH="/var/lib/rancher/k3s/server/join-token.env"

    if [[ "$(hostname)" == "master-01" ]]; then
      echo "Bootstrapping primary control-plane node with --cluster-init"
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="$K3S_VERSION" sh -s - server \
        --cluster-init \
        --tls-san "$MASTER_IP" \
        --disable traefik \
        --disable servicelb \
        --disable local-storage \
        --disable flannel \
        --cluster-cidr=10.244.0.0/16 \
        --service-cidr=10.96.0.0/12

      echo "Waiting for Kubernetes API to be available..."
      until kubectl get nodes &>/dev/null; do sleep 5; done

      echo "Retrieving K3s join token..."
      K3S_JOIN_TOKEN=$(kubectl get secret -n kube-system k3s-join-token -o jsonpath='{.data.token}' | base64 --decode)
      echo "K3S_JOIN_TOKEN=$K3S_JOIN_TOKEN" > "$JOIN_TOKEN_PATH"

      # Deploy Sealed Secrets Controller
      echo "Deploying Sealed Secrets Controller..."
      kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.23.1/controller.yaml

    else
      echo "Joining existing K3s cluster..."
      echo "Waiting for join token..."
      until [ -f "$JOIN_TOKEN_PATH" ]; do
          echo "Join token not found, retrying in 5s..."
          sleep 5
      done
      source "$JOIN_TOKEN_PATH"

      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="$K3S_VERSION" sh -s - agent \
        --server "https://$MASTER_IP:6443" \
        --token "$K3S_JOIN_TOKEN"
    fi
