apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  labels:
    app: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
      - name: dex
        # Official Dex image, pinned to a version you prefer:
        image: ghcr.io/dexidp/dex:v2.35.3
        ports:
        - containerPort: 5556
