apiVersion: v1
kind: Service
metadata:
  name: dex
  labels:
    app: dex
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5556
      protocol: TCP
      targetPort: 5556
  selector:
    app: dex
