apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-ssm-global
  # "ClusterSecretStore" is cluster-wide, so typically goes in "default" or another
  # special NS. Up to you. Some folks also just use "SecretStore" in a single namespace.
  namespace: default
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        # This example uses a secret with your AWS credentials.
        # In production, you'd prefer IRSA or a better method.
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            namespace: default
            key: access_key_id
          secretAccessKeySecretRef:
            name: aws-creds
            namespace: default
            key: secret_access_key
