apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: web
spec:
  project: default
  source:
    path: apps/nginx
  destination:
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
