apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.25.150.10-10.25.150.10
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vip-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - vip-pool
