apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  source:
    repoURL: 'https://github.com/theepicsaxguy/argocd-app-of-apps.git'
    targetRevision: main
    path: appsets          # Points to the folder containing our "all-apps.yaml"
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
