apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: 'git@github.com:theepicsaxguy/argocd-app-of-apps.git'
    path: argocd
    targetRevision: main
  project: default
  syncPolicy:
    automated: 
      prune: true 
      allowEmpty: true
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
