apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  source:
    repoURL: 'git@github.com:theepicsaxguy/argocd-app-of-apps.git'
    path: apps
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated: 
      prune: true 
      allowEmpty: true
      selfHeal: true 
