apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  source:
    repoURL: 'git@github.com:theepicsaxguy/argocd-app-of-apps.git'
    path: apps
    targetRevision: master
    directory:
      recurse: true
      exclude: '{config.json,wireguard/*}'
      include: '*.yaml,*.yml'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
