apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-scheduler-config
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    # Example: your custom scheduling policy
    profiles:
    - schedulerName: custom-scheduler
      plugins:
        queueSort:
          enabled:
            - name: PrioritySort
