apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  labels:
    app: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      serviceAccountName: custom-scheduler
      containers:
      - name: custom-scheduler
        image: k8s.gcr.io/kube-scheduler:v1.26.0
        command:
          - kube-scheduler
          - --config=/etc/kubernetes/config/scheduler-config.yaml
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes/config
      volumes:
      - name: scheduler-config
        configMap:
          name: custom-scheduler-config
