apiVersion: apps/v1
kind: Deployment
metadata:
  name: descheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: descheduler
  template:
    metadata:
      labels:
        app: descheduler
    spec:
      containers:
        - name: descheduler
          image: k8s.gcr.io/descheduler/descheduler:v0.27.0
          command:
            - "/bin/descheduler"
            - "--policy-config-file"
            - "/policy-dir/policy.yaml"
            - "--v"
            - "2"
          volumeMounts:
            - mountPath: "/policy-dir"
              name: policy-volume
      volumes:
        - name: policy-volume
          configMap:
            name: descheduler-policy