name: Linters and utilities
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  yaml-linter:
    name: Yaml Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
        with:
          config_file: .yamllint
      - run: echo ${{ steps.yaml-lint.outputs.logfile }}
