name: Linters and utilities
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
- name: Renovate Bot GitHub Action
  uses: renovatebot/github-action@9ad1a8e771c002ece340d1ff028fae4503fe041b # v41.0.12