name: Linters and utilities
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
- name: Renovate Bot GitHub Action
  uses: renovatebot/github-action@3f10d7a25cf0aa7b37519aa771ed9143fcbb5da5 # v41.0.10