name: Linters and utilities
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
- name: Renovate Bot GitHub Action
  uses: renovatebot/github-action@d385c88822a237acaead89c462fa0aef7502748f # v41.0.11