name: Linters and utilities
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  renovate:
    name: Renovate Bot GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@02f4fdeb479bbb229caa7ad82cb5e691c07e80b3 # v41.0.14
