name: Terraform Linter
on: [pull_request]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Check if Terraform files changed
        id: terraform-changes
        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45
        with:
          files: |
            terraform/**
      - name: Tailscale
        if: steps.terraform-changes.outputs.any_changed == 'true'
        uses: tailscale/github-action@8688eb839e58e6b25c1ae96cd99d1c173299b842 # v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:clients
      - name: Clone repo
        if: steps.terraform-changes.outputs.any_changed == 'true'
        uses: actions/checkout@master
      - name: Install Terraform
        if: steps.terraform-changes.outputs.any_changed == 'true'
        run: |
          curl iac.sh/terraform > getinst.sh && \
          bash getinst.sh
      - name: Terraform init
        if: steps.terraform-changes.outputs.any_changed == 'true'
        run: |
          cd terraform && \
          terraform init -upgrade -backend-config="conn_str=${{ secrets.tf_con_string }}"
      - name: tflint
        if: steps.terraform-changes.outputs.any_changed == 'true'
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: "terraform"
          reporter: github-pr-review
          fail_on_error: "true"
          flags: "--module"
          filter_mode: "nofilter"
